version: '3.8'

services:
  web:
    build : ./src
    command: python -u app.py
    volumes : 
      - ./src:/src
    ports :
      - 5002:80
    depends_on:
      - mongodb
      - redisdb

  mongodb:
    image: mongo
  
  redisdb:
    image: redis